//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Products
    {
        public int Cart_Product_Id { get; set; }
        public int CartId { get; set; }
        public int ProductId { get; set; }
        public int ProductAmountInCart { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Products Products { get; set; }
    }
}
